apiVersion: v1
kind: Service
metadata:
  name: velocity-svc
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    app: velocity  # 대상 파드의 레이블
  ports:
    - protocol: TCP
      port: 25565   # 서비스의 노출 포트
      targetPort: 25565  # 파드의 컨테이너 포트
  type: LoadBalancer  # LoadBalancer 타입 지정

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: velocity-deployment
  namespace: default
  labels:
    app: velocity
spec:
  replicas: 3
  selector:
    matchLabels:
      app: velocity
  template:
    metadata:
      labels:
        app: velocity
    spec:
      containers:
      - name: velocity-container
        image: 756266714368.dkr.ecr.ap-northeast-2.amazonaws.com/velocity:17
        ports:
        - containerPort: 25565

